{% set name = "lua-luaposix" %}
{% set version = "36.2.1" %}

package:
  name: {{ name }} 
  version: {{ version }}

source:
  url: https://github.com/luaposix/luaposix/archive/v{{ version }}.tar.gz
  sha256: 44e5087cd3c47058f9934b90c0017e4cf870b71619f99707dd433074622debb1

build:
  number: 0
  ## osx lua build is broken, see https://github.com/conda-forge/lua-feedstock/pull/40
  skip: true  # [not linux]
  rpaths:
    - lib/lua/5.4/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - zlib
    - luarocks
    - lua
    - perl
  run:
    - lua
    - luarocks

test:
  commands:
    - lua -e "require 'posix'"

about:
  home: 'http://luaposix.github.io/luaposix/'
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'This is a POSIX binding for LuaJIT, Lua 5.1, 5.2 and 5.3'
  description: |
       This is a POSIX binding for LuaJIT, Lua 5.1, 5.2, 5.3 and 5.4; like most libraries
       it simply binds to C APIs on the underlying system, so it won't work on
       non-POSIX systems. However, it does try to detect the level of POSIX
       conformance of the underlying system and bind only available APIs.

extra:
  recipe-maintainers:
    - jerowe
    - izahn
