{% set name = "lua-luaposix" %}
{% set version = "35.0" %}
{% set sha256 = "9039570555fc7133e747880a78f9f5cc9bdfa759113e152566497d6f234bba20" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name.split('-')[1] }}/luaposix/archive/release-v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  fn: {{ name }}-{{ version }}.tar.gz

build:
  detect_binary_files_with_prefix: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gcc  # [linux]
    - llvm  # [osx]
    - zlib 1.2.*
    - luarocks
    - lua
    - perl

  run:
    - libgcc  # [linux]
    - zlib 1.2.*
    - lua
    - luarocks
    - perl

test:
  commands:
    - lua -e "require 'posix'"

about:
  home: http://luaposix.github.io/luaposix/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: This is a POSIX binding for LuaJIT, Lua 5.1, 5.2 and 5.3
  description: |
    This is a POSIX binding for LuaJIT, Lua 5.1, 5.2 and 5.3; like most libraries
    it simply binds to C APIs on the underlying system, so it won't work on
    non-POSIX systems. However, it does try to detect the level of POSIX
    conformance of the underlying system and bind only available APIs.

extra:
  recipe-maintainers:
    - jerowe
