travis:
  secure:
    BINSTAR_TOKEN: AWeM0kbJ2+RGzD7XWP2kpgu3c8X8nHU+The59hXyCv8cz8JFEswaUr/mQQt7FjMyMXI3bO6MWJknWrzhSXfMZ1tjYbhCWtO8PAsf6EAF0+MV0tNsh/PIU61J8d7OcBZoFv3qGkM24LLsgg17i0BXjUuzIE61E3GAGWkBSWDo0OXe+cvDgdV0Vj5KQCOx3iuVxrX4YciPH7cxQV2F0cT+02AKWWGSe8FRSuXHvT5rXwm9uk1eHrUdSbsg6SQJVoRTOFZLRd5Mmyc9VVgnd23EWAS/njcEb2uSGJnItxtgiBRbcvPOHzKkfipDtdqQR5Jc3Ds3SBc6ITBc0UVUnpPvXVY1elL688zOwHQAheyvXT9bbtuJ6l1RdUwpH9BCZDZAd5D0MBDR3YqJFM0MGRn+jIyXp1rfrI0pXIhg47hqw48AiD7bz4//5p6n3JtL4XWvU/5pvUkjOe97ciYQ3rC/pHOYVL5PyPneDqrK4fUZteCC/m1zqCOAIyVq47ggcIT70OuO9RQovhVCmjYciyoUvIMi2tOEfyku05eWXZQAmrkXoy3qt6MLlurvTanoF0RJROB/lfw5dVRp3M6/CEyr5bMcv6LxH8VrlExkuhu22D4FcSVRjt0QfG9bYeEB8VK3NVPtnQ2Cdzzbo8ffyi06uV9buFtYUvNVQRs7hoCXXXg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
